export * from "./types";
export { PluginManager } from "./plugin-manager";
export {
  registerRightPanel,
  unregisterRightPanel,
  openRightPanel,
  collapseRightPanel,
  closeRightPanel,
  getActiveRightPanel,
  setActiveRightPanelDock,
  moveActiveRightPanelDock,
  getActiveRightPanelDock,
  RIGHT_PANEL_DOCKS,
  isRightPanelCollapsed,
  getRightPanel,
  listRightPanels,
  getRightPanelSnapshot,
  subscribeRightPanels,
  type RightPanelSnapshot,
  type RightPanelDock,
} from "./right-panel-registry";
export {
  registerToolbarMenu,
  unregisterToolbarMenu,
  listToolbarMenus,
  getToolbarMenusSnapshot,
  subscribeToolbarMenus,
  type ToolbarMenusSnapshot,
  type ToolbarMenuEntry,
} from "./toolbar-menu-registry";
export {
  registerFloatingPanel,
  unregisterFloatingPanel,
  openFloatingPanel,
  closeFloatingPanel,
  focusFloatingPanel,
  isFloatingPanelOpen,
  getOpenFloatingPanels,
  getFloatingPanel,
  getFloatingPanelsSnapshot,
  subscribeFloatingPanels,
  type FloatingPanelsSnapshot,
} from "./floating-panel-registry";
export { maplibreLayerControlPlugin } from "./plugins/layer-control";
export { osmBasemapPlugin } from "./plugins/osm-basemap";
export { cartoLightPlugin } from "./plugins/carto-light";
export {
  maplibreBasemapControlPlugin,
  setBasemapControlLabels,
  type BasemapControlLabels,
} from "./plugins/maplibre-basemap-control";
export {
  addArcGISLayer,
  type ArcGISLayerOptions,
  type ArcGISLayerType,
  type ArcGISSourceType,
} from "./plugins/arcgis-layer";
export {
  addCogRasterLayer,
  closeBookmarkPanel,
  closeColorbarPanel,
  closeHtmlPanel,
  closeLegendPanel,
  closeMaplibreComponentControls,
  closeMeasurePanel,
  closeMinimapPanel,
  closePrintPanel,
  closeSearchPlacesPanel,
  closeSpinGlobePanel,
  closeViewStatePanel,
  isBookmarkPanelVisible,
  isColorbarPanelVisible,
  isHtmlPanelVisible,
  isLegendPanelVisible,
  isMeasurePanelVisible,
  isMinimapPanelVisible,
  isPrintPanelVisible,
  isSearchPlacesPanelVisible,
  isSpinGlobePanelVisible,
  isViewStatePanelVisible,
  COMPONENTS_PLUGIN_ID,
  maplibreComponentsPlugin,
  openBookmarkPanel,
  openFlatGeobufAddVectorLayerPanel,
  openColorbarPanel,
  openHtmlPanel,
  openLegendPanel,
  openLidarLayerPanel,
  openMeasurePanel,
  openMinimapPanel,
  openPMTilesLayerPanel,
  openPrintPanel,
  openSearchPlacesPanel,
  openSpinGlobePanel,
  openSplattingLayerPanel,
  openStacSearchLayerPanel,
  openViewStatePanel,
  openZarrLayerPanel,
  addCloudNetcdfLayer,
  type CloudNetcdfLayerOptions,
  setBookmarkLabels,
  subscribeBookmarkPanel,
  subscribeColorbarPanel,
  subscribeHtmlPanel,
  subscribeLegendPanel,
  subscribeMeasurePanel,
  subscribeMinimapPanel,
  subscribePrintPanel,
  subscribeSearchPlacesPanel,
  subscribeSpinGlobePanel,
  subscribeViewStatePanel,
  type CogRasterLayerOptions,
} from "./plugins/maplibre-components";
export {
  KerchunkReferenceStore,
  loadKerchunkReference,
  listKerchunkVariables,
  normalizeKerchunkReference,
  type KerchunkRefs,
  type KerchunkVariable,
} from "./plugins/kerchunk-reference-store";
export {
  closeDuckDBLayerPanel,
  getDuckDBFeatureBounds,
  getDuckDBLayerRows,
  identifyDuckDBLayerAtPoint,
  openDuckDBLayerPanel,
  setDuckDBSelectedFeature,
  updateDuckDBLayerRows,
  type DuckDBAttributeRow,
  type DuckDBIdentifyResult,
} from "./plugins/maplibre-duckdb";
export {
  closePlanetaryComputerPanel,
  openPlanetaryComputerPanel,
} from "./plugins/maplibre-planetary-computer";
export {
  closeEarthEnginePanel,
  isEarthEnginePanelVisible,
  openEarthEnginePanel,
  subscribeEarthEnginePanel,
  toggleEarthEnginePanel,
} from "./plugins/maplibre-earth-engine";
export {
  closeThreeDTilesLayerPanel,
  openThreeDTilesLayerPanel,
  restoreThreeDTilesLayers,
} from "./plugins/maplibre-3d-tiles";
export { isRecoverableNonTiledRasterError } from "./plugins/non-tiled-raster-error";
export {
  addRasterToMap,
  applyRasterLayerOrder,
  closeRasterLayerPanel,
  openRasterLayerPanel,
  restoreRasterLayers,
  setNonTiledRasterHandler,
  setRasterPixelInspect,
  type NonTiledRasterRequest,
} from "./plugins/maplibre-raster";
export {
  RASTER_MAX_CLASSES,
  RASTER_MIN_CLASSES,
  RASTER_MIN_CUSTOM_COLORS,
  type RasterBandStats,
  type RasterClassificationMethod,
  type RasterSymbology,
  clampRasterClassCount,
  computeRasterBreaks,
  defaultRasterSymbology,
  savedRasterSymbology,
} from "./plugins/raster-symbology";
export {
  RASTER_SOURCE_KIND,
  getRasterBandStats,
} from "./plugins/raster-symbology-texture";
export { colormapColors, warmColormapColors } from "./plugins/colormap-colors";
export {
  closeVectorLayerPanel,
  materializeEmbeddableVectorLayers,
  openVectorLayerPanel,
  reloadVectorControlLayer,
  restoreVectorLayers,
  setKmlFileImportHandler,
  isKmlFileSelection,
  routeKmlFileSelection,
  type KmlFileImport,
  type KmlFileImportHandler,
} from "./plugins/maplibre-vector";
// The raster-layer-sync and vector-layer-sync internals are not
// re-exported: the app drives the panels through the functions above, and
// the tests import the sync helpers from the module paths directly.
export {
  clearDirectionsWaypoints,
  DIRECTIONS_PLUGIN_ID,
  getDirectionsWaypointCount,
  isDirectionsRemovalInFlight,
  maplibreDirectionsPlugin,
  removeLastDirectionsWaypoint,
  restoreDirections,
  subscribeDirectionsState,
} from "./plugins/maplibre-directions";
export {
  REVERSE_GEOCODE_PLUGIN_ID,
  maplibreReverseGeocodePlugin,
  restoreReverseGeocode,
  setReverseGeocodeLabels,
  type ReverseGeocodeLabels,
} from "./plugins/maplibre-reverse-geocode";
export {
  DEFAULT_EFFECTS_SETTINGS,
  EFFECTS_PLUGIN_ID,
  type EffectsSettings,
  getEffectsSettings,
  HALO_EXTENT_MAX,
  HALO_EXTENT_MIN,
  HALO_OPACITY_MAX,
  HALO_OPACITY_MIN,
  maplibreEffectsPlugin,
  restoreEffects,
  setEffectsSettings,
} from "./plugins/maplibre-effects";
export {
  DECK_VIZ_PLUGIN_ID,
  maplibreDeckGlVizPlugin,
} from "./plugins/maplibre-deckgl-viz";
export { restoreDeckViz } from "./plugins/deckgl-viz/overlay";
export { ensureMercatorProjection } from "./plugins/map-projection-utils";
export {
  DECK_VIZ_CATEGORY_LABELS,
  DEFAULT_DECK_VIZ_SCENEGRAPH,
  DEFAULT_DECK_VIZ_STYLE,
  getDeckVizLayerDef,
  listDeckVizLayerDefs,
  type DeckVizCategory,
  type DeckVizConfig,
  type DeckVizFieldMapping,
  type DeckVizFormat,
  type DeckVizInputKind,
  type DeckVizLayerDef,
  type DeckVizRole,
  type DeckVizScenegraphConfig,
  type DeckVizStyle,
  type DeckVizStyleControl,
} from "./plugins/deckgl-viz/registry";
export {
  createDeckVizStoreLayer,
  DECK_VIZ_SOURCE_KIND,
  isDeckVizLayer,
} from "./plugins/deckgl-viz/store-layer";
export {
  maplibreAnnotationsPlugin,
  ANNOTATIONS_SOURCE_KIND,
  setAnnotationLabels,
  type AnnotationLabels,
} from "./plugins/maplibre-annotations";
export { maplibreEnviroAtlasPlugin } from "./plugins/maplibre-enviroatlas";
export { maplibreEsriWaybackPlugin } from "./plugins/maplibre-esri-wayback";
export { maplibreFemaWmsPlugin } from "./plugins/maplibre-fema-wms";
export {
  maplibreGeoEditorPlugin,
  canEditLayerGeometry,
  SKETCHES_SOURCE_KIND,
  startLayerGeometryEdit,
  endLayerGeometryEdit,
  getGeometryEditTargetLayerId,
  subscribeGeometryEdit,
} from "./plugins/maplibre-geo-editor";
export { maplibreGeoAgentPlugin } from "./plugins/maplibre-geoagent";
export { maplibreUsgsLidarPlugin } from "./plugins/maplibre-usgs-lidar";
export { maplibreNasaEarthdataPlugin } from "./plugins/maplibre-nasa-earthdata";
export { maplibreNationalMapPlugin } from "./plugins/maplibre-national-map";
export { maplibreOvertureMapsPlugin } from "./plugins/maplibre-overture-maps";
export { maplibreStreetViewPlugin } from "./plugins/maplibre-streetview";
export { maplibreSwipePlugin } from "./plugins/maplibre-swipe";
export {
  maplibreGraticulePlugin,
  GRATICULE_PLUGIN_ID,
  GRATICULE_LABEL_LAYER_ID,
  DEFAULT_GRATICULE_SETTINGS,
  DEFAULT_GRATICULE_LABELS,
  getGraticuleSettings,
  setGraticuleSettings,
  setGraticuleLabels,
  normalizeGraticuleSettings,
  type GraticuleSettings,
  type GraticuleLabels,
  type GraticuleLabelFormat,
  type GraticuleLabelEdges,
} from "./plugins/maplibre-graticule";
export {
  maplibreH3Plugin,
  H3_PLUGIN_ID,
  H3_VIEWPORT_CELL_LIMIT,
  DEFAULT_H3_GRID_SETTINGS,
  DEFAULT_H3_LABELS,
  getH3GridSettings,
  setH3GridSettings,
  setH3Labels,
  normalizeH3GridSettings,
  h3LabelMinZoom,
  h3ResolutionForZoom,
  h3CellFeature,
  h3GridForBounds,
  h3FixTransmeridianBoundary,
  type H3GridSettings,
  type H3Labels,
} from "./plugins/maplibre-h3";
export {
  maplibreS2Plugin,
  S2_PLUGIN_ID,
  MAX_S2_LEVEL,
  S2_VIEWPORT_CELL_LIMIT,
  DEFAULT_S2_GRID_SETTINGS,
  DEFAULT_S2_LABELS,
  getS2GridSettings,
  setS2GridSettings,
  setS2Labels,
  normalizeS2GridSettings,
  s2LabelMinZoom,
  s2LevelForZoom,
  s2CellFeature,
  s2GridForBounds,
  type S2GridSettings,
  type S2Labels,
} from "./plugins/maplibre-s2";
export { DGGS_PLUGIN_IDS } from "./plugins/dggs-group";
export {
  maplibreA5Plugin,
  A5_PLUGIN_ID,
  A5_VIEWPORT_CELL_LIMIT,
  DEFAULT_A5_GRID_SETTINGS,
  DEFAULT_A5_LABELS,
  getA5GridSettings,
  setA5GridSettings,
  setA5Labels,
  normalizeA5GridSettings,
  a5LabelMinZoom,
  a5ResolutionForZoom,
  a5CellFeature,
  a5GridForBounds,
  type A5GridSettings,
  type A5Labels,
} from "./plugins/maplibre-a5";
export {
  maplibreDggridPlugin,
  DGGRID_PLUGIN_ID,
  DGGRID_CONFIG,
  DGGRID_TOPOLOGIES,
  DGGRID_PROJECTIONS,
  DGGRID_APERTURES,
  MAX_DGGRID_RESOLUTION,
  DGGRID_VIEWPORT_CELL_LIMIT,
  DEFAULT_DGGRID_GRID_SETTINGS,
  DEFAULT_DGGRID_LABELS,
  getDggridGridSettings,
  setDggridGridSettings,
  setDggridLabels,
  normalizeDggridGridSettings,
  dggridLabelMinZoom,
  dggridResolutionForZoom,
  dggridCellFeature,
  dggridGridForBounds,
  loadDggrid,
  type DggridGridSettings,
  type DggridLabels,
  type DggridTopology,
  type DggridProjection,
  type DggridAperture,
} from "./plugins/maplibre-dggrid";
export {
  maplibreDggalPlugin,
  DGGAL_PLUGIN_ID,
  DGGAL_TYPES,
  DGGAL_TYPE_NAMES,
  DGGAL_VIEWPORT_CELL_LIMIT,
  DEFAULT_DGGAL_GRID_SETTINGS,
  DEFAULT_DGGAL_LABELS,
  getDggalGridSettings,
  setDggalGridSettings,
  setDggalLabels,
  normalizeDggalGridSettings,
  dggalLabelMinZoom,
  dggalResolutionForZoom,
  dggalZoneFeature,
  dggalParentZones,
  dggalGridForBounds,
  loadDggal,
  type DggalGridSettings,
  type DggalLabels,
  type DggalType,
  type DggalEngine,
  type DggalDggrs,
} from "./plugins/maplibre-dggal";
export {
  maplibreOlcPlugin,
  OLC_PLUGIN_ID,
  OLC_CODE_LENGTHS,
  OLC_VIEWPORT_CELL_LIMIT,
  MAX_OLC_CODE_LENGTH,
  DEFAULT_OLC_GRID_SETTINGS,
  DEFAULT_OLC_LABELS,
  getOlcGridSettings,
  setOlcGridSettings,
  setOlcLabels,
  normalizeOlcGridSettings,
  olcLabelMinZoom,
  olcResolutionForZoom,
  olcCellFeature,
  olcGridForBounds,
  olcParentCell,
  olcChildCount,
  olcNeighborCells,
  type OlcGridSettings,
  type OlcLabels,
  type OlcCodeLength,
} from "./plugins/maplibre-olc";
export {
  maplibreGeohashPlugin,
  GEOHASH_PLUGIN_ID,
  GEOHASH_VIEWPORT_CELL_LIMIT,
  GEOHASH_CHILDREN_PER_CELL,
  MIN_GEOHASH_PRECISION,
  MAX_GEOHASH_PRECISION,
  DEFAULT_GEOHASH_GRID_SETTINGS,
  DEFAULT_GEOHASH_LABELS,
  getGeohashGridSettings,
  setGeohashGridSettings,
  setGeohashLabels,
  normalizeGeohashGridSettings,
  geohashLabelMinZoom,
  geohashResolutionForZoom,
  geohashCellFeature,
  geohashGridForBounds,
  geohashParentCell,
  geohashNeighborCells,
  type GeohashGridSettings,
  type GeohashLabels,
} from "./plugins/maplibre-geohash";
export {
  maplibreTilecodePlugin,
  TILECODE_PLUGIN_ID,
  TILECODE_VIEWPORT_CELL_LIMIT,
  TILECODE_CHILDREN_PER_CELL,
  MIN_TILECODE_ZOOM,
  MAX_TILECODE_ZOOM,
  DEFAULT_TILECODE_GRID_SETTINGS,
  DEFAULT_TILECODE_LABELS,
  getTilecodeGridSettings,
  setTilecodeGridSettings,
  setTilecodeLabels,
  normalizeTilecodeGridSettings,
  tilecodeLabelMinZoom,
  tilecodeResolutionForZoom,
  tilecodeCellFeature,
  tilecodeGridForBounds,
  tilecodeParentCell,
  tilecodeNeighborCells,
  tileToTilecode,
  tilecodeToTile,
  tileToQuadkey,
  pointToTile,
  type Tile,
  type TilecodeGridSettings,
  type TilecodeLabels,
} from "./plugins/maplibre-tilecode";
export type { WeatherAnimationState, WeatherLayerController } from "./plugins/weather-layer";
export {
  maplibreCloudsPlugin,
  CLOUDS_PLUGIN_ID,
  getCloudsAnimationState,
  setCloudsFrame,
  toggleCloudsPlaying,
  subscribeClouds,
} from "./plugins/maplibre-clouds";
export {
  maplibrePrecipitationPlugin,
  PRECIPITATION_PLUGIN_ID,
  getPrecipitationAnimationState,
  setPrecipitationFrame,
  togglePrecipitationPlaying,
  subscribePrecipitation,
} from "./plugins/maplibre-precipitation";
export {
  maplibreTimeSliderPlugin,
  TIME_SLIDER_PLUGIN_ID,
  getLayerTimeBinding,
} from "./plugins/maplibre-time-slider";
export {
  buildTimeBinding,
  buildTimeFilter,
  detectTimeProperties,
  type TimeBinding,
  type TimeGranularity,
  type TimePropertyCandidate,
  type TimeValueKind,
  type TimeWindow,
} from "./plugins/time-slider-binding";
export { WEB_SERVICE_PLUGIN_IDS } from "./plugins/web-service-sync";
